# run_name: 
# experiment_name: 
# comet_project_name: 
# gpu_id:
# cuda: 
# num_workers:

# train:
#   data_dir: '/mnt/ialabnas/datasets/CLEVR_v1.0/images/train'
#   batch_size: 32
#   epochs: 100
#   snapshot_interval: 5
#   it_log_interval: 200
  
#   model:

#   optimizer:
#     model:
#       name:
#       params:
#         lr:
#       schedule: [
#         name:
#         params:

#       ]

# model:
#   sub_model_params:
